version: "2"
services:
    minimap:
        build: .
        restart: unless-stopped
        networks:
            - frontend
        labels:
            traefik.backend: minimap
            traefik.port: 80
            traefik.enabled: true

networks:
    frontend:
        external: true
