version: "2"
services:
    minimap:
        build: .
        restart: unless-stopped
        networks:
            frontend: null
            webserver:
                aliases:
                    - minimap-server
        expose:
            - "80"
        labels:
            traefik.backend: minimap
            traefik.port: "80"
            traefik.enable: "true"
            traefik.host: "minimap"
            traefik.domain: "erindachtler.me"

networks:
    frontend:
        external: true
    webserver:
        external: true
