version: "2"
services:
    minimap:
        build: .
        restart: unless-stopped
        networks:
            - frontend
        labels:
            traefik.backend: minimap

networks:
    frontend:
        external: true
