version: "2"
services:
    minimap:
        build: .
        restart: always
        networks:
            - frontend
        labels:
            traefik.backend: minimap

networks:
    frontend:
        external: true
