version: "2"
services:
    minimap:
        build: .
        restart: unless-stopped
        networks:
            - frontend
        labels:
            traefik.backend: minimap
            traefik.port: "80"
            traefik.enable: "true"
            traefik.host: "minimap.erindachtler.me"

networks:
    frontend:
        external: true
