version: "2"
services:
    minimap:
        build: .
        restart: unless-stopped
        networks:
            webserver:
                aliases:
                    - minimap-server
        expose:
            - "80"

networks:
    webserver:
        external: true
